---

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - xdm
    - expect
    - nano
    - chromium-browser
    - tightvncserver
    - xfce4
    - xfce4-goodies
  become: yes
  become_method: sudo

- name: Add VNC user {{ vnc_user }} for vnc
  user:
     name: {{ vnc_user }}

- name: Install authorized ssh key for user {{ vnc_user }}
  authorized_key:
    user: {{ vnc_user }}
    state: present
    key: {{ vnc_ssh_pub_key }}

    
- name: Check whether /etc/ssh/sshd_config contains "127.0.0.1:5901"
  command: grep -Fxq "127.0.0.1:5901" /etc/ssh/sshd_config
  register: checksshdconf
  check_mode: no
  ignore_errors: yes
  changed_when: no

- name: Greet the world if /tmp/my.conf contains "127.0.0.1"
  debug: msg="Hello, world!"
  when: checkmyconf.rc == 0
    
- name: Prepare OpenSSH Tunnel Config File
  shell:
    cmd: |
      cat <<EOL >> /tmp/sshd_config
      Match User {{ vnc_user }}
      PermitOpen 127.0.0.1:5901
      X11Forwarding no
      AllowAgentForwarding no
      ForceCommand /bin/false
      EOL
  when: checksshdconf.rc == 1
  become: yes
  become_method: sudo

- name: Add OpenSSH Tunnel Config
  shell: sudo bash -c "cat /tmp/sshd_config >> /etc/ssh/sshd_config"
  when: checksshdconf.rc == 1
  become: yes
  become_method: sudo

- name: Remove temp OpenSSH Tunnel Config
  shell: rm /tmp/sshd_config
  when: checksshdconf.rc == 1
  become: yes
  become_method: sudo

- name: restart sshd
  service: name=sshd state=restarted
  when: checksshdconf.rc == 1
  become: yes
  become_method: sudo