---

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - xdm
    - expect
    - nano
    - chromium-browser
    - tightvncserver
    - xfce4
    - xfce4-goodies
  become: yes
  become_method: sudo

- name: Add VNC user {{ vnc_user }} for vnc
  user:
    name: "{{ vnc_user }}"
    shell: /bin/bash
    home: /home/{{ vnc_user}}
  become: yes
  become_method: sudo

- name: Install authorized ssh key for user {{ vnc_user }}
  authorized_key:
    user: "{{ vnc_user }}"
    state: present
    key: "{{ lookup('file', 'vnc_ssh.pub') }}"
  become: yes
  become_method: sudo
    
- name: Check whether /etc/ssh/sshd_config contains "127.0.0.1:5901"
  command: grep -Fxq "127.0.0.1:5901" /etc/ssh/sshd_config
  register: checksshdconf
  check_mode: no
  ignore_errors: yes
  changed_when: no
    
- name: Prepare OpenSSH Tunnel Config File
  shell:
    cmd: |
      cat <<EOL >> /tmp/sshd_config
      Match User {{ vnc_user }}
      PermitOpen 127.0.0.1:5901
      X11Forwarding no
      AllowAgentForwarding no
      ForceCommand /bin/false
      EOL
  when: checksshdconf.rc == 1
  become: yes
  become_method: sudo

- name: Add OpenSSH Tunnel Config
  shell: "cat /tmp/sshd_config >> /etc/ssh/sshd_config"
  when: checksshdconf.rc == 1
  become: yes
  become_method: sudo

- name: Remove temp OpenSSH Tunnel Config
  file: 
     path: /tmp/sshd_config
     state: absent
  when: checksshdconf.rc == 1
  become: yes
  become_method: sudo

- name: restart sshd
  service: name=sshd state=restarted
  when: checksshdconf.rc == 1
  become: yes
  become_method: sudo

- name: "Create the remote /{{ vnc_user }}/.vnc directory"
  file:
     path: "/home/{{ vnc_user }}/.vnc"
     mode: 0755
     state: directory
  become: yes
  become_user: "{{ vnc_user }}"

- name: "Generate vnc password for user {{ vnc_user }}  remotely"
  shell: |
        echo {{ vnc_password}}  | vncpasswd -f > /home/{{ vnc_user }}/.vnc/passwd
  become: yes
  become_user: "{{ vnc_user }}"
- name: "Change the permission to 600 for /{{ vnc_user }}/.vnc/passwd file"
  file:
      path: "/home/{{ vnc_user }}/.vnc/passwd"
      mode: 0600
  become: yes
  become_user: "{{ vnc_user }}"
- name: Start VNC Server
  shell: 'sudo -iu {{ vnc_user }} vncserver -depth 16 -geometry 1280x1024 :1'
  register: vncstart
  failed_when: vncstart.rc !=0 and vncstart.rc!=98
  become: yes
