---

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - xdm
    - expect
    - nano
    - chromium-browser
    - tightvncserver
    - xfce4
    - xfce4-goodies
  become: yes
  become_method: sudo

- name: Add VNC user {{ vnc_user }} for vnc 
  shell: adduser {{ vnc_user }} --gecos "" --disabled-password
  become: yes
  become_method: sudo


- name: Create .ssh directory
  shell: mkdir /home/{{ vnc_user }}/.ssh
  become: yes
  become_method: sudo

- name: Create .ssh directory
  shell: bash -c "echo ssh-rsa {{ vnc_ssh_pub_key }}  >> /home/{{ vnc_user }}/.ssh/authorized_keys"
  become: yes
  become_method: sudo

- name: Prepare OpenSSH Tunnel Config File
  shell:
    cmd: |
      cat <<EOL >> /tmp/sshd_config
      Match User {{ vnc_user }}
      PermitOpen 127.0.0.1:5901
      X11Forwarding no
      AllowAgentForwarding no
      ForceCommand /bin/false
      EOL
  become: yes
  become_method: sudo

- name: Add OpenSSH Tunnel Config
  shell: sudo bash -c "cat /tmp/sshd_config >> /etc/ssh/sshd_config"
  become: yes
  become_method: sudo

- name: Remove temp OpenSSH Tunnel Config
  shell: rm /tmp/sshd_config
  become: yes
  become_method: sudo

- name: restart sshd
  service: name=sshd state=restarted
  become: yes
  become_method: sudo