---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster
  become: yes
  become_method: sudo

- name: Kubeadm Init
  shell: kubeadm init --apiserver-advertise-address=172.24.1.2 --pod-network-cidr=10.244.0.0/16
  become: yes
  become_method: sudo

- command: mkdir -p /home/kubernetes/.kube
  become: yes
  become_method: sudo


- command: cp /etc/kubernetes/admin.conf /home/kubernetes/.kube/config
  become: yes
  become_method: sudo

- command: chown -R kubernetes:kubernetes /home/kubernetes/.kube
  become: yes
  become_method: sudo

- template:
    src: kube-flannel.yml
    dest: /tmp/kube-flannel.yml
  become: yes
  become_method: sudo
  become_user: kubernetes  

- command: kubectl create -f /tmp/kube-flannel.yml
  become: yes
  become_method: sudo
  become_user: kubernetes

- command: kubeadm token create --print-join-command > /joincluster.sh
  become: yes
  become_method: sudo
