---

- name: Apply configuration to all k8s master nodes
  hosts: k8s-master-nodes
  remote_user: root
  roles:
    - docker
    - k8s-instance
    - k8s-master 
  environment:
    http_proxy: management-station:3128
    https_proxy: management-station:3128

- name: Apply configuration to all k8s worker nodes
  hosts: k8s-worker-nodes
  remote_user: root
  roles:
    - docker
    - k8s-instance
    - k8s-worker
  environment:
    http_proxy: management-station:3128
    https_proxy: management-station:3128
    
- name: Apply configuration to proxy server
  hosts: proxy-nodes
  remote_user: root
  roles:
    - docker
    - proxy-server

- name: Apply configuration to vnc server
  hosts: vnc-nodes
  remote_user: root
  roles:
    - vnc